Background
----------

This is a high-level overview of the Ashtadhyayi and how it works.

.. toctree::
    :maxdepth: 2

    introduction
    terms
    sounds
    rule_types
    glossary


Architecture
------------

This describes the overall architecture of the system.

.. toctree::
    :maxdepth: 2


API Reference
-------------

This contains information about specific classes, functions, and methods.

.. toctree::
    :maxdepth: 2

    api

